import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Hybrid",
  description: "How Hybrid collects, uses, and protects your data.",
};

const UPDATED = "June 23, 2026";
const CONTACT = "cmrod34@gmail.com";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl sm:text-2xl font-bold text-white mb-4">{title}</h2>
      <div className="space-y-3 text-white/55 text-[15px] leading-relaxed">{children}</div>
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#080a0f] px-6 py-20">
      <div className="max-w-3xl mx-auto">
        {/* Back link */}
        <Link href="/" className="text-[#00e5ff] text-sm font-medium hover:text-white transition-colors">
          ← Back to Hybrid
        </Link>

        {/* Header */}
        <h1 className="text-4xl sm:text-5xl font-black text-white mt-8 mb-3">Privacy Policy</h1>
        <p className="text-white/35 text-sm mb-12">Last updated: {UPDATED}</p>

        <Section title="Who we are">
          <p>
            Hybrid (&ldquo;Hybrid,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) provides AI-assisted training
            and nutrition guidance for hybrid athletes through our website (hybridfit.org) and mobile app.
            This policy explains what we collect, why, and the choices you have.
          </p>
        </Section>

        <Section title="Information we collect">
          <p><strong className="text-white/80">Account information:</strong> your email address and an encrypted password when you create an account.</p>
          <p><strong className="text-white/80">Profile &amp; fitness inputs:</strong> information you choose to enter to generate plans — such as athlete type, goals, experience level, training days, available equipment, session length, upcoming events, and any injuries or notes you provide.</p>
          <p><strong className="text-white/80">Nutrition inputs:</strong> if you use nutrition features, optional details like body weight, height, age, gender, activity level, dietary restrictions, and food preferences.</p>
          <p><strong className="text-white/80">Waitlist &amp; feedback:</strong> if you join our waitlist or submit feedback, the email address and responses you provide.</p>
          <p><strong className="text-white/80">Technical data:</strong> basic, standard server logs (such as request times and error logs) used to operate and secure the service.</p>
        </Section>

        <Section title="How we use your information">
          <ul className="list-disc pl-5 space-y-2">
            <li>To create your account and let you sign in.</li>
            <li>To generate your personalized training and nutrition plans.</li>
            <li>To respond to feedback and send updates you&rsquo;ve asked for.</li>
            <li>To operate, secure, debug, and improve the service.</li>
          </ul>
          <p>We do <strong className="text-white/80">not</strong> sell your personal information, and we do not use it for third-party advertising.</p>
        </Section>

        <Section title="Service providers we share data with">
          <p>To run Hybrid, we share limited data with trusted providers that process it on our behalf:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong className="text-white/80">Anthropic</strong> — your plan inputs are sent to Anthropic&rsquo;s Claude API to generate your training and nutrition plans.</li>
            <li><strong className="text-white/80">Supabase</strong> — stores your account and authentication data.</li>
            <li><strong className="text-white/80">Vercel</strong> — hosts our website and backend.</li>
            <li><strong className="text-white/80">Google</strong> — waitlist and feedback submissions may be recorded in Google Sheets and sent to us by email.</li>
          </ul>
          <p>These providers are bound to use the data only to provide their services to us.</p>
        </Section>

        <Section title="Health &amp; wellness disclaimer">
          <p>
            Hybrid provides general fitness and nutrition information generated by AI. It is{" "}
            <strong className="text-white/80">not medical advice</strong>, and we are not a healthcare
            provider. Plans and macro estimates are for informational purposes only. Always consult a
            qualified physician or registered dietitian before starting any new training or nutrition
            program, particularly if you have an injury, medical condition, allergy, or eating disorder.
          </p>
        </Section>

        <Section title="Data retention">
          <p>
            We keep your information for as long as your account is active or as needed to provide the
            service. You can request deletion of your account and associated data at any time (see below).
          </p>
        </Section>

        <Section title="Security">
          <p>
            We use industry-standard measures to protect your data, including encrypted connections and
            managed authentication. No method of transmission or storage is 100% secure, but we work to
            protect your information and limit access to it.
          </p>
        </Section>

        <Section title="Your rights">
          <p>
            You can access, correct, or delete your personal information. To request deletion of your
            account or a copy of your data, email us at{" "}
            <a href={`mailto:${CONTACT}`} className="text-[#00e5ff] hover:text-white transition-colors">{CONTACT}</a>{" "}
            and we&rsquo;ll respond within a reasonable time.
          </p>
        </Section>

        <Section title="Children">
          <p>
            Hybrid is not directed to children under 13, and we do not knowingly collect personal
            information from them. If you believe a child has provided us data, contact us and we will
            delete it.
          </p>
        </Section>

        <Section title="Changes to this policy">
          <p>
            We may update this policy from time to time. When we do, we&rsquo;ll revise the &ldquo;Last
            updated&rdquo; date above. Material changes will be communicated through the app or website.
          </p>
        </Section>

        <Section title="Contact us">
          <p>
            Questions about this policy or your data? Email{" "}
            <a href={`mailto:${CONTACT}`} className="text-[#00e5ff] hover:text-white transition-colors">{CONTACT}</a>.
          </p>
        </Section>

        <div className="border-t border-white/10 pt-8 mt-12">
          <Link href="/" className="text-[#00e5ff] text-sm font-medium hover:text-white transition-colors">
            ← Back to Hybrid
          </Link>
        </div>
      </div>
    </main>
  );
}
